### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Uzzi** [akscf/iscdhcp-admin#1]
Hi, I'm using isc-dhcp-manager-1.0.0-17052019, where can I set EN language?

Regards

**Comment by aks-tel** [comment]
Hi
You can do it in the application settings 
(but you need to reload a page after that, seems there's a some bug in language manager...)

See attachment.
![switch_lng](https://user-images.githubusercontent.com/14818067/62776815-b2545500-babc-11e9-97e5-194afa0d00b1.png)

**Comment by aks-tel** [comment]
fixed in version: isc-dhcp-manager-1.0.0-26092019
